targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: vi
          fallback_strategy: base_locale
          input_directory: lib/i18n # Make sure this matches the path to your i18n folder
          namespaces: true # Enable namespaces for subdirectories like 'game' and 'intro'
          output_directory: lib/gen
          output_file_name: translations.g.dart
