name: flutter_loto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flame: ^1.22.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  just_audio: ^0.9.42
  slang: ^4.4.0
  slang_flutter: ^4.4.0
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  mobile_scanner: ^6.0.3
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.13
  slang_build_runner: ^4.4.0
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/icons/
    - assets/icons/svgs/
    - assets/icons/pngs/
